# Generated by Django 6.0.7 on 2026-07-27 02:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MedicationCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Medication',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('generic_name', models.CharField(blank=True, max_length=200, null=True)),
                ('manufacturer', models.CharField(max_length=200)),
                ('strength', models.CharField(max_length=100)),
                ('unit', models.CharField(choices=[('TABLET', 'Tablet'), ('CAPSULE', 'Capsule'), ('ML', 'Milliliter'), ('MG', 'Milligram'), ('GM', 'Gram'), ('VIAL', 'Vial'), ('POUCH', 'Pouch')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('requires_prescription', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='medications', to='inventory.medicationcategory')),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('minimum_threshold', models.IntegerField(default=10)),
                ('batch_number', models.CharField(max_length=100)),
                ('expiry_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='clinics.clinic')),
                ('medication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock', to='inventory.medication')),
            ],
            options={
                'unique_together': {('clinic', 'medication', 'batch_number')},
            },
        ),
    ]
