# Generated by Django 6.0.7 on 2026-07-27 02:20

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clinics', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AnimalSpecies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('scientific_name', models.CharField(blank=True, max_length=200, null=True)),
                ('common_breeds', models.JSONField(default=list)),
            ],
        ),
        migrations.CreateModel(
            name='AnimalPatient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('animal_id', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
                ('species', models.CharField(choices=[('POULTRY', 'Poultry'), ('CATTLE', 'Cattle'), ('GOAT', 'Goat/Sheep'), ('DOG', 'Dog'), ('CAT', 'Cat'), ('HORSE', 'Horse'), ('OTHER', 'Other')], max_length=20)),
                ('breed', models.CharField(blank=True, max_length=100, null=True)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age', models.IntegerField(help_text='Age in months')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True)),
                ('color', models.CharField(blank=True, max_length=50, null=True)),
                ('identification_tags', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('TREATING', 'Under Treatment'), ('RECOVERED', 'Recovered'), ('DECEASED', 'Deceased'), ('REFERRED', 'Referred')], default='ACTIVE', max_length=20)),
                ('last_visit', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('clinic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patients', to='clinics.clinic')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
